[[redirects]]
  from = "/blog"
  to = "https://l.facebook.com/l.php?u=https%3A%2F%2Fmedium.com%2F%40wfn%2Ftoxic-productivity-comparison-cultures-impact-on-university-students-cdfda6dff5f8%3Ffbclid%3DIwAR1SSVBNe_sNZYsjxhWlu7EdWq6kSqwiQRy_sawrcOTNOS_g6JZYfJfoYKg&h=AT3A8hjJ5Proim8qbtM8eUUFjgP2vot0Jbv7otJRRR-yeeNWnk6wBXQWjMsuwwWzB_so3ZN6xJGfOq0UcRHDLKfK8j0a_67L42Jpqdo0qBd3R8F71iScVGBG_fAQyZH7ULXscqPCF_8"
  status = 302